image:
  file: .gitpod.Dockerfile
ports:
  - port: 8002
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
  - port: 1025
    onOpen: ignore
  - port: 8025
    onOpen: open-browser
tasks:
  - name: composer
    init: composer install && exit
  - name: mysql
    init: |
      gp await-port 3306
      mysql -e "CREATE DATABASE wordpress;"
      mysql -e "CREATE USER 'wordpress'@'localhost' IDENTIFIED by 'wordpress';"
      mysql -e "GRANT ALL ON wordpress.* to 'wordpress'@'localhost';"
      bunzip2 < sql/provision.sql.bz2 | mysql wordpress
  - name: nginx
    command: >
      nginx &&
      multitail /var/log/nginx/access.log -I /var/log/nginx/error.log
  - name: php8.1-fpm
    command: sudo service php8.1-fpm start
  - name: Redis
    command: redis-server
  - name: Mailhog
    init: docker pull mailhog/mailhog
    command: docker run -p 8025:8025 -p 1025:1025 mailhog/mailhog
  - name: npm
    init: cd www/wp-content/themes/anika && npm install
    command: www/wp-content/themes/anika && npm run watch

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - johnbillion.vscode-wordpress-hooks
    - felixfbecker.php-debug
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true