image:
  file: .gitpod.Dockerfile
tasks:
  - name: composer
    init: composer install && exit
  - name: mysql
    init: |
      gp await-port 3306
      mysql -e "CREATE DATABASE wordpress;"
      mysql -e "CREATE USER 'wordpress'@'localhost' IDENTIFIED by 'wordpress';"
      mysql -e "GRANT ALL ON wordpress.* to 'wordpress'@'localhost';"
  - name: wp-tests
    init: svn co https://develop.svn.wordpress.org ./wp-tests
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - johnbillion.vscode-wordpress-hooks
    - felixfbecker.php-debug
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true